openapi: 3.0.0
info:
  title: Go Cinema Rest Api Spec
  description: >
    `Design First`, `Validated`
  version: project.version
servers:
  - url: "/"
tags:
  - name: Users
    description: Пользователи
paths:
  /users:
    get:
      summary: Получение всех пользователей
      operationId: getUsers
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        login:
          type: string
          description: Логин
          example: "laba"
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        description:
          type: string
          description: Текст ошибки
          example: "Упс!"